name: "Build Addon"

on: [pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Container
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target babybuddy \
            --docker-hub svihra
